# Generated by Django 4.2.20 on 2025-04-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_checksum_file_is_duplicate_file_reference_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='is_duplicate',
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['checksum'], name='checksum_idx'),
        ),
    ]
